services:
  finances_statements:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_user
        - github_token
    container_name: finances_statements
    restart: always
    ports:
      - "8081:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
    secrets:
      - github_user
      - github_token

  statements_listener:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_user
        - github_token
    container_name: statements_listener
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
    secrets:
      - github_user
      - github_token
    entrypoint: ["python", "-m", "finances_statements.listener"]

networks:
  finances-network:
    external: true

secrets:
  github_user:
    file: ./secrets/github_user.txt
  github_token:
    file: ./secrets/github_token.txt
